// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetPartialSchemaResponse - The schema for a partial
// +k8s:openapi-gen=false
type GetPartialSchemaResponse struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	Fields []map[string]any `json:"fields,omitempty"`
}

func (o *GetPartialSchemaResponse) GetFields() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Fields
}
