// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProviderName - Name of cloud provider.
// +k8s:openapi-gen=true
type ProviderName string

const (
	ProviderNameAws   ProviderName = "aws"
	ProviderNameAzure ProviderName = "azure"
)

func (e ProviderName) ToPointer() *ProviderName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProviderName) IsExact() bool {
	if e != nil {
		switch *e {
		case "aws", "azure":
			return true
		}
	}
	return false
}
