//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright © 2024 Kong Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

package components

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/Kong/sdk-konnect-go/models/components.Active":                      schema_Kong_sdk_konnect_go_models_components_Active(ref),
		"github.com/Kong/sdk-konnect-go/models/components.CreateControlPlaneRequest":   schema_Kong_sdk_konnect_go_models_components_CreateControlPlaneRequest(ref),
		"github.com/Kong/sdk-konnect-go/models/components.CreateNetworkRequest":        schema_Kong_sdk_konnect_go_models_components_CreateNetworkRequest(ref),
		"github.com/Kong/sdk-konnect-go/models/components.CreateTransitGatewayRequest": schema_Kong_sdk_konnect_go_models_components_CreateTransitGatewayRequest(ref),
		"github.com/Kong/sdk-konnect-go/models/components.Destinations":                schema_Kong_sdk_konnect_go_models_components_Destinations(ref),
		"github.com/Kong/sdk-konnect-go/models/components.Healthchecks":                schema_Kong_sdk_konnect_go_models_components_Healthchecks(ref),
		"github.com/Kong/sdk-konnect-go/models/components.Healthy":                     schema_Kong_sdk_konnect_go_models_components_Healthy(ref),
		"github.com/Kong/sdk-konnect-go/models/components.Passive":                     schema_Kong_sdk_konnect_go_models_components_Passive(ref),
		"github.com/Kong/sdk-konnect-go/models/components.ProxyURL":                    schema_Kong_sdk_konnect_go_models_components_ProxyURL(ref),
		"github.com/Kong/sdk-konnect-go/models/components.Sources":                     schema_Kong_sdk_konnect_go_models_components_Sources(ref),
		"github.com/Kong/sdk-konnect-go/models/components.Unhealthy":                   schema_Kong_sdk_konnect_go_models_components_Unhealthy(ref),
		"github.com/Kong/sdk-konnect-go/models/components.UpstreamClientCertificate":   schema_Kong_sdk_konnect_go_models_components_UpstreamClientCertificate(ref),
		"github.com/Kong/sdk-konnect-go/models/components.UpstreamHealthy":             schema_Kong_sdk_konnect_go_models_components_UpstreamHealthy(ref),
		"github.com/Kong/sdk-konnect-go/models/components.UpstreamUnhealthy":           schema_Kong_sdk_konnect_go_models_components_UpstreamUnhealthy(ref),
	}
}

func schema_Kong_sdk_konnect_go_models_components_Active(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"concurrency": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"headers": {
						SchemaProps: spec.SchemaProps{
							Description: "A map of header names to arrays of header values.",
							Type:        []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type: []string{"array"},
										Items: &spec.SchemaOrArray{
											Schema: &spec.Schema{
												SchemaProps: spec.SchemaProps{
													Default: "",
													Type:    []string{"string"},
													Format:  "",
												},
											},
										},
									},
								},
							},
						},
					},
					"healthy": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.Healthy"),
						},
					},
					"http_path": {
						SchemaProps: spec.SchemaProps{
							Description: "A string representing a URL path, such as /path/to/resource. Must start with a forward slash (/) and must not contain empty segments (i.e., two consecutive forward slashes).",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"https_sni": {
						SchemaProps: spec.SchemaProps{
							Description: "A string representing an SNI (server name indication) value for TLS.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"https_verify_certificate": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"timeout": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"number"},
							Format: "double",
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"unhealthy": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.Unhealthy"),
						},
					},
				},
				Required: []string{"concurrency", "http_path", "https_verify_certificate", "timeout", "type"},
			},
		},
		Dependencies: []string{
			"github.com/Kong/sdk-konnect-go/models/components.Healthy", "github.com/Kong/sdk-konnect-go/models/components.Unhealthy"},
	}
}

func schema_Kong_sdk_konnect_go_models_components_CreateControlPlaneRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CreateControlPlaneRequest - The request schema for the create control plane request.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Description: "The name of the control plane.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"description": {
						SchemaProps: spec.SchemaProps{
							Description: "The description of the control plane in Konnect.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"cluster_type": {
						SchemaProps: spec.SchemaProps{
							Description: "The ClusterType value of the cluster associated with the Control Plane.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"auth_type": {
						SchemaProps: spec.SchemaProps{
							Description: "The auth type value of the cluster associated with the Runtime Group.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"cloud_gateway": {
						SchemaProps: spec.SchemaProps{
							Description: "Whether this control-plane can be used for cloud-gateways.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"proxy_urls": {
						SchemaProps: spec.SchemaProps{
							Description: "Array of proxy URLs associated with reaching the data-planes connected to a control-plane.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/Kong/sdk-konnect-go/models/components.ProxyURL"),
									},
								},
							},
						},
					},
					"labels": {
						SchemaProps: spec.SchemaProps{
							Description: "Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.\n\nKeys must be of length 1-63 characters, and cannot start with \"kong\", \"konnect\", \"mesh\", \"kic\", or \"_\".",
							Type:        []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
				},
				Required: []string{"name"},
			},
		},
		Dependencies: []string{
			"github.com/Kong/sdk-konnect-go/models/components.ProxyURL"},
	}
}

func schema_Kong_sdk_konnect_go_models_components_CreateNetworkRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CreateNetworkRequest - Request schema for creating a network.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Description: "Human-readable name of the network.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"cloud_gateway_provider_account_id": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"region": {
						SchemaProps: spec.SchemaProps{
							Description: "Region ID for cloud provider region.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"availability_zones": {
						SchemaProps: spec.SchemaProps{
							Description: "List of availability zones that the network is attached to.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"cidr_block": {
						SchemaProps: spec.SchemaProps{
							Description: "CIDR block configuration for the network.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"state": {
						SchemaProps: spec.SchemaProps{
							Description: "Initial state for creating a network.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"name", "cloud_gateway_provider_account_id", "region", "availability_zones", "cidr_block", "state"},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_CreateTransitGatewayRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CreateTransitGatewayRequest - Request schema for creating a transit gateway.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"AWSTransitGateway": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.AWSTransitGateway"),
						},
					},
					"AWSVpcPeeringGateway": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.AWSVpcPeeringGateway"),
						},
					},
					"AWSResourceEndpointGateway": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.AWSResourceEndpointGateway"),
						},
					},
					"AzureTransitGateway": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.AzureTransitGateway"),
						},
					},
					"GcpVpcPeeringTransitGateway": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.GcpVpcPeeringTransitGateway"),
						},
					},
					"Type": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
				},
				Required: []string{"AWSTransitGateway", "AWSVpcPeeringGateway", "AWSResourceEndpointGateway", "AzureTransitGateway", "GcpVpcPeeringTransitGateway", "Type"},
			},
		},
		Dependencies: []string{
			"github.com/Kong/sdk-konnect-go/models/components.AWSResourceEndpointGateway", "github.com/Kong/sdk-konnect-go/models/components.AWSTransitGateway", "github.com/Kong/sdk-konnect-go/models/components.AWSVpcPeeringGateway", "github.com/Kong/sdk-konnect-go/models/components.AzureTransitGateway", "github.com/Kong/sdk-konnect-go/models/components.GcpVpcPeeringTransitGateway"},
	}
}

func schema_Kong_sdk_konnect_go_models_components_Destinations(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"ip": {
						SchemaProps: spec.SchemaProps{
							Description: "A string representing an IP address or CIDR block, such as 192.168.1.1 or 192.168.0.0/16.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"port": {
						SchemaProps: spec.SchemaProps{
							Description: "An integer representing a port number between 0 and 65535, inclusive.",
							Type:        []string{"integer"},
							Format:      "int64",
						},
					},
				},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_Healthchecks(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Healthchecks - The array of healthchecks.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"active": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.Active"),
						},
					},
					"passive": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.Passive"),
						},
					},
					"threshold": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"number"},
							Format: "double",
						},
					},
				},
				Required: []string{"threshold"},
			},
		},
		Dependencies: []string{
			"github.com/Kong/sdk-konnect-go/models/components.Active", "github.com/Kong/sdk-konnect-go/models/components.Passive"},
	}
}

func schema_Kong_sdk_konnect_go_models_components_Healthy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"http_statuses": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: 0,
										Type:    []string{"integer"},
										Format:  "int64",
									},
								},
							},
						},
					},
					"interval": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"number"},
							Format: "double",
						},
					},
					"successes": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
				},
				Required: []string{"interval", "successes"},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_Passive(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"healthy": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.UpstreamHealthy"),
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"unhealthy": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Kong/sdk-konnect-go/models/components.UpstreamUnhealthy"),
						},
					},
				},
				Required: []string{"type"},
			},
		},
		Dependencies: []string{
			"github.com/Kong/sdk-konnect-go/models/components.UpstreamHealthy", "github.com/Kong/sdk-konnect-go/models/components.UpstreamUnhealthy"},
	}
}

func schema_Kong_sdk_konnect_go_models_components_ProxyURL(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProxyURL - Proxy URL associated with reaching the data-planes connected to a control-plane.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"host": {
						SchemaProps: spec.SchemaProps{
							Description: "Hostname of the proxy URL.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"port": {
						SchemaProps: spec.SchemaProps{
							Description: "Port of the proxy URL.",
							Default:     0,
							Type:        []string{"integer"},
							Format:      "int64",
						},
					},
					"protocol": {
						SchemaProps: spec.SchemaProps{
							Description: "Protocol of the proxy URL.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"host", "port", "protocol"},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_Sources(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"ip": {
						SchemaProps: spec.SchemaProps{
							Description: "A string representing an IP address or CIDR block, such as 192.168.1.1 or 192.168.0.0/16.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"port": {
						SchemaProps: spec.SchemaProps{
							Description: "An integer representing a port number between 0 and 65535, inclusive.",
							Type:        []string{"integer"},
							Format:      "int64",
						},
					},
				},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_Unhealthy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"http_failures": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"http_statuses": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: 0,
										Type:    []string{"integer"},
										Format:  "int64",
									},
								},
							},
						},
					},
					"interval": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"number"},
							Format: "double",
						},
					},
					"tcp_failures": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"timeouts": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
				},
				Required: []string{"http_failures", "interval", "tcp_failures", "timeouts"},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_UpstreamClientCertificate(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "UpstreamClientCertificate - If set, the certificate to be used as client certificate while TLS handshaking to the upstream server.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"id": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_UpstreamHealthy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"http_statuses": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: 0,
										Type:    []string{"integer"},
										Format:  "int64",
									},
								},
							},
						},
					},
					"successes": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
				},
				Required: []string{"successes"},
			},
		},
	}
}

func schema_Kong_sdk_konnect_go_models_components_UpstreamUnhealthy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"http_failures": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"http_statuses": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: 0,
										Type:    []string{"integer"},
										Format:  "int64",
									},
								},
							},
						},
					},
					"tcp_failures": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"timeouts": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
				},
				Required: []string{"http_failures", "tcp_failures", "timeouts"},
			},
		},
	}
}
